title: Ashton Harrell
description: CS Student @ Louisiana Tech | Open to Work
url: "https://ashx004.github.io"
author:
  name: Ashton Harrell
  email: ashx004@gmail.com
  github: ashx004
  linkedin: axharrell
favicon: /favicon.png